title: SGE
description: Sistemes de Gestió Empresarial
theme: just-the-docs

url: https://jaume-av.github.io/SGE/
baseurl: "/SGE" 

aux_links:
  "Accés a Aules":
    - https://aules.edu.gva.es/fp/

search_enabled: true

footer:
  copyright: "© 2024 Jaume"
  links:
    - title: "Llicència CC BY-SA 4.0"
      url: "https://creativecommons.org/licenses/by-sa/4.0/"

# Navegació directa sense desplegables
collections:
  docs:
    output: true
    permalink: /:path/